package com.aifds.backend.audit.entity;

public enum AuditReasonCode {
    CASE_REQUIRED_BY_RISK_POLICY,
    CASE_REVIEW_STARTED,
    CASE_ADDITIONAL_INFORMATION_REQUESTED,
    CASE_REVIEW_RESUMED,
    CASE_ASSIGNEE_ASSIGNED,
    CASE_ASSIGNEE_CHANGED,
    CASE_ASSIGNEE_RELEASED,
    RISK_RESPONSE_DECIDED_BY_POLICY,
    TRANSACTION_FINALIZED_BY_RISK_POLICY
}
