CREATE TABLE ai_report_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id UUID NOT NULL UNIQUE,
    fraud_case_id BIGINT NOT NULL REFERENCES fraud_case(id) ON DELETE RESTRICT,
    detection_result_id BIGINT NOT NULL REFERENCES detection_result(id) ON DELETE RESTRICT,
    detection_result_version INTEGER NOT NULL CHECK (detection_result_version >= 1),
    prompt_version VARCHAR(64) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('PENDING','GENERATING','COMPLETED','FALLBACK_COMPLETED','FAILED')),
    failure_code VARCHAR(64),
    lease_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    CONSTRAINT uq_ai_execution_key UNIQUE (fraud_case_id, detection_result_version, prompt_version, model_version, execution_id)
);
CREATE UNIQUE INDEX uq_ai_execution_active ON ai_report_execution
    (fraud_case_id, detection_result_version, prompt_version, model_version)
    WHERE status IN ('PENDING','GENERATING');

CREATE TABLE ai_report_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_request_id UUID NOT NULL UNIQUE,
    fraud_case_id BIGINT NOT NULL REFERENCES fraud_case(id) ON DELETE RESTRICT,
    execution_id BIGINT REFERENCES ai_report_execution(id) ON DELETE RESTRICT,
    report_id BIGINT,
    idempotency_key VARCHAR(128) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    detection_result_version INTEGER NOT NULL CHECK (detection_result_version >= 1),
    prompt_version VARCHAR(64) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('PENDING','GENERATING','COMPLETED','FALLBACK_COMPLETED','FAILED')),
    cache_hit BOOLEAN NOT NULL DEFAULT false,
    execution_shared BOOLEAN NOT NULL DEFAULT false,
    trace_id VARCHAR(64) NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_ai_request_idempotency UNIQUE (fraud_case_id, idempotency_key)
);
CREATE INDEX ix_ai_request_case_latest ON ai_report_request(fraud_case_id, requested_at DESC, ai_request_id DESC);

CREATE TABLE ai_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id UUID NOT NULL UNIQUE,
    fraud_case_id BIGINT NOT NULL REFERENCES fraud_case(id) ON DELETE RESTRICT,
    execution_id BIGINT NOT NULL UNIQUE REFERENCES ai_report_execution(id) ON DELETE RESTRICT,
    detection_result_version INTEGER NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    report_status VARCHAR(24) NOT NULL CHECK (report_status IN ('COMPLETED','FALLBACK_COMPLETED')),
    report_source VARCHAR(24) NOT NULL CHECK (report_source IN ('LLM','TEMPLATE_FALLBACK')),
    summary VARCHAR(600) NOT NULL,
    key_reasons JSONB NOT NULL,
    timeline_summary VARCHAR(240) NOT NULL,
    investigation_checklist JSONB NOT NULL,
    failure_code VARCHAR(64),
    trace_id VARCHAR(64) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_ai_report_key ON ai_report(fraud_case_id, detection_result_version, prompt_version, model_version);
ALTER TABLE ai_report_request ADD CONSTRAINT fk_ai_request_report
    FOREIGN KEY (report_id) REFERENCES ai_report(id) ON DELETE RESTRICT;

CREATE TABLE provider_call_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL REFERENCES ai_report_execution(id) ON DELETE RESTRICT,
    attempt_number INTEGER NOT NULL CHECK (attempt_number BETWEEN 1 AND 2),
    provider VARCHAR(32) NOT NULL,
    model_digest VARCHAR(128),
    quantization VARCHAR(64),
    input_tokens INTEGER CHECK (input_tokens >= 0),
    output_tokens INTEGER CHECK (output_tokens >= 0),
    latency_ms INTEGER NOT NULL CHECK (latency_ms >= 0),
    outcome VARCHAR(32) NOT NULL,
    estimated_cost NUMERIC(18, 6),
    cost_currency CHAR(3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_provider_attempt_number UNIQUE (execution_id, attempt_number)
);
