CREATE TABLE ai_report_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(64) NOT NULL CHECK (event_type = 'AiReportExecutionCreated'),
    event_version INTEGER NOT NULL CHECK (event_version = 1),
    execution_id UUID NOT NULL UNIQUE REFERENCES ai_report_execution(execution_id) ON DELETE RESTRICT,
    payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CLAIMED', 'PUBLISHED', 'BLOCKED')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 10),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claim_token UUID,
    lease_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    last_failure_code VARCHAR(64),
    CONSTRAINT ck_ai_outbox_claim CHECK (
        (status = 'CLAIMED' AND claim_token IS NOT NULL AND lease_until IS NOT NULL)
        OR (status <> 'CLAIMED' AND claim_token IS NULL AND lease_until IS NULL)
    ),
    CONSTRAINT ck_ai_outbox_published CHECK (
        (status = 'PUBLISHED' AND published_at IS NOT NULL)
        OR (status <> 'PUBLISHED' AND published_at IS NULL)
    )
);
CREATE INDEX ix_ai_outbox_ready ON ai_report_outbox(next_attempt_at, id)
    WHERE status IN ('PENDING', 'CLAIMED');
