package com.aifds.backend.idempotency.service;

public enum IdempotencyRecoveryDecision {
    RECOVERABLE_COMPLETION_GAP,
    ANALYZED_FINALIZED,
    UNLINKED_CLAIM_TERMINATED,
    RECEIVED_TERMINATED,
    ANALYZING_TERMINATED,
    CONFIRMED_FAILURE_TERMINATED,
    MAINTENANCE_PRECONDITION_FAILED,
    LOCK_CONTENTION,
    MISSING_IDEMPOTENCY_RECORD,
    MISSING_TRANSACTION,
    PROCESSING_INDETERMINATE,
    FINALIZATION_INCOMPLETE,
    CONFIRMED_DOMAIN_FAILURE,
    INCONSISTENT_FINAL_STATE,
    INCONSISTENT_CASE_RELATIONSHIP,
    FINALIZATION_AUDIT_MISMATCH,
    CONFLICTING_IDEMPOTENCY_DATA,
    ALREADY_TERMINAL,
    INTERNAL_FAILURE
}
