package com.aifds.backend.rule.client;

public enum RuleAnalysisClientErrorCategory {
    AI_SERVICE_REQUEST_CONTRACT_ERROR,
    AI_SERVICE_PAYLOAD_TOO_LARGE,
    AI_SERVICE_RULE_CONTRACT_ERROR,
    AI_SERVICE_CAPABILITY_MISMATCH,
    AI_SERVICE_INTERNAL_ERROR,
    AI_SERVICE_CONNECT_TIMEOUT,
    AI_SERVICE_RESPONSE_TIMEOUT,
    AI_SERVICE_UNAVAILABLE,
    AI_SERVICE_INVALID_RESPONSE
}
